force-app/main/default/objects/Account/fields/LinkedIn_URL__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_URL__c</fullName>
    <description>LinkedIn URL</description>
    <label>LinkedIn URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Experience_Reference__c.field-meta.xml
<CustomField>
    <fullName>Primary_Experience_Reference__c</fullName>
    <description>Sets the Account&#39;s primary reference to show experience on Opportunity</description>
    <label>Primary Experience Reference</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LinkedIn</fullName>
                <default>true</default>
                <label>LinkedIn</label>
            </value>
            <value>
                <fullName>Trailhead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Trailhead_URL__c.field-meta.xml
<CustomField>
    <fullName>Trailhead_URL__c</fullName>
    <description>Salesforce Trailhead profile URL</description>
    <label>Trailhead URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Experience_URL__c.field-meta.xml
<CustomField>
    <fullName>Experience_URL__c</fullName>
    <defaultValue>&quot;https://www.linkedin.com/in/jason-snyder2/&quot;</defaultValue>
    <description>URL for LinkedIn or Trailhead</description>
    <label>Experience URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Description__c.field-meta.xml
<CustomField>
    <fullName>Interest_Description__c</fullName>
    <description>Text description to show interest.</description>
    <label>Interest Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
/**
 *  @description Trigger handler for the Account Object
 *  @auther Jason Snyder
 *  @created 09/20/2019
 */

public without sharing class AccountTriggerHandler {
    
    /**
     * @description After Update Trigger Handler
     * @method handleAfterUpdate
     * @param oldAccountMap Map of Account Ids and old verisions of Account records
     * @param newAccountMap Map of Account Ids and new verisions of Account records
     */
    public static void handleAfterUpdate(Map<Id,Account> oldAccountMap, Map<Id,Account> newAccountMap) {
        try {
            updateOpportunityExperienceField(oldAccountMap, newAccountMap);
        }
        catch(Exception ex) {
            System.debug(ex.getMessage());
        }
    }

    /**
     * @description Updates the Experience_URL__c and Interest_Description__c fields on Opportunity
                    based on the value in Account Primary_Experience_Reference__c field
     * @method updateOpportunityExperienceField
     * @param oldAccountMap Map of Account Ids and old verisions of Account records
     * @param newAccountMap Map of Account Ids and new verisions of Account records
     */
    private static void updateOpportunityExperienceField(Map<Id,Account> oldAccountMap, Map<Id,Account> newAccountMap) {
        Map<Id,Account> changedAccountMap = getChangedAccounts(oldAccountMap, newAccountMap);
        List<Opportunity> oppList = new List<Opportunity>();
        // Get Child Opportunities
        if(changedAccountMap.size() > 0) {
            oppList = [SELECT Id, Name, AccountId, Experience_URL__c, Interest_Description__c FROM Opportunity WHERE AccountId in: changedAccountMap.keySet()];
            if(oppList.size() > 0) {
                updateOppList(oppList, changedAccountMap);
            }
        }
    }

    /**
     * @description Get a Map of account Ids and records that have the Primary_Experience_Reference__c field changed
     * @method getChangedAccounts
     * @param oldAccountMap Map of Account Ids and old verisions of Account records
     * @param newAccountMap Map of Account Ids and new verisions of Account records
     * @return Map of Account Record Ids and records that Primary_Experience_Reference__c field value has changed
     */
    private static Map<Id, Account> getChangedAccounts(Map<Id,Account> oldAccountMap, Map<Id,Account> newAccountMap) {
        Map<Id,Account> changedAccountMap = new Map<Id,Account>();

        for(Account acc : newAccountMap.values()) {
            // If Primary_Experience_Reference__c value different add to list
            if(acc.Primary_Experience_Reference__c != oldAccountMap.get(acc.Id).Primary_Experience_Reference__c) {
                changedAccountMap.put(acc.Id, acc);
            }
        }

        return changedAccountMap;
    }

    /**
     * @description Set child opportunites of accountMap accounts fields: Experience_URL__c and Interest_Description__c
                    based on Account Primary_Experience_Reference__c field LinkedIn or Trailhead
     * @method updateOppList
     * @param oppList List of child opportunites from accountMap accounts
     * @param accountMap Map of Account Record Ids and records that Primary_Experience_Reference__c field value has changed
     */
    private static void updateOppList(List<Opportunity> oppList, Map<Id, Account> accountMap) {
        for(Opportunity opp : oppList) {
            Account acc = accountMap.get(opp.AccountId);
            switch on acc.Primary_Experience_Reference__c {
                when 'LinkedIn' {
                    opp.Experience_URL__c = acc.LinkedIn_URL__c;
                    opp.Interest_Description__c = Label.Hire_on_LinkedIn;
                }
                when 'Trailhead' {
                    opp.Experience_URL__c = acc.Trailhead_URL__c;
                    opp.Interest_Description__c = Label.Hire_on_Trailhead;
                }
            }
        }

        update oppList;
    }
}